"""
Quietlyy — Facebook/Instagram Poster
3-layer fallback: Facebook Reel → Facebook Video → manual save
Since FB and IG are linked, posting to one auto-posts to both.
SEO metadata and AI disclosure are generated by generate_seo.py.
"""

import os
import json
import requests

GRAPH_API = "https://graph.facebook.com/v22.0"
FB_UPLOAD_API = "https://rupload.facebook.com/video-upload/v22.0"


def get_credentials():
    page_id = os.environ.get("FB_PAGE_ID")
    token = os.environ.get("FB_PAGE_ACCESS_TOKEN")
    if not page_id or not token:
        raise ValueError("FB_PAGE_ID and FB_PAGE_ACCESS_TOKEN must be set")
    return page_id, token


def get_page_token(page_id, token):
    """
    Exchange any valid token (User, System User, or Page) for a Page Access Token.
    Page Access Tokens are required by the Reels and video upload endpoints.
    If the token is already a Page token, this is a no-op.
    """
    resp = requests.get(
        f"{GRAPH_API}/{page_id}",
        params={"access_token": token, "fields": "access_token,name,id"},
        timeout=10,
    )
    if resp.status_code == 200:
        data = resp.json()
        page_token = data.get("access_token")
        if page_token and page_token != token:
            print(f"[facebook] Exchanged System User token → Page Access Token for '{data.get('name')}'")
            return page_token
    # Already a page token or exchange not possible — use as-is
    return token


def verify_credentials():
    """Pre-flight check: verify token works and page is accessible.
    Prints debug info. Raises on hard failure."""
    page_id, token = get_credentials()
    print(f"[facebook] Pre-flight check (page_id={page_id})...")

    # 1. Check the token is valid at all
    me_resp = requests.get(
        f"{GRAPH_API}/me",
        params={"access_token": token, "fields": "name,id"},
        timeout=10,
    )
    if me_resp.status_code != 200:
        raise ValueError(f"Token invalid — /me returned {me_resp.status_code}: {me_resp.text[:300]}")
    me = me_resp.json()
    print(f"[facebook] Token valid for: {me.get('name')} (id={me.get('id')})")

    # 2. Check the page is accessible
    page_resp = requests.get(
        f"{GRAPH_API}/{page_id}",
        params={"access_token": token, "fields": "name,id,fan_count"},
        timeout=10,
    )
    if page_resp.status_code != 200:
        raise ValueError(
            f"Page {page_id} not accessible — {page_resp.status_code}: {page_resp.text[:300]}\n"
            f"HINT: FB_PAGE_ID should be the numeric Page ID from /me/accounts, "
            f"NOT the profile.php?id= number."
        )
    page = page_resp.json()
    print(f"[facebook] Page found: '{page.get('name')}' (id={page.get('id')}, followers={page.get('fan_count', 'unknown')})")


def build_description(topic, script_text):
    """Fallback description builder (used only if SEO metadata not provided)."""
    lines = [line.strip() for line in script_text.split("\n") if line.strip()]
    caption = "\n".join(lines)
    return (
        f"{caption}\n\n"
        f"— Quietlyy\n\n"
        f"#Quietlyy #{topic.replace(' ', '')} #nostalgia #memories "
        f"#deepthoughts #lifequotes #reflection #lostmoments\n\n"
        f"AI assistance was used in the making of this video."
    )


def _raise_with_body(resp):
    """Raise HTTPError with full API response body for debugging."""
    try:
        resp.raise_for_status()
    except requests.HTTPError as e:
        raise requests.HTTPError(
            f"{e} | API response: {resp.text[:500]}", response=resp
        ) from e


# ── Layer 1: Facebook Reel (best reach) ──
def post_as_reel(video_path, description):
    page_id, raw_token = get_credentials()
    # Exchange System User token → Page Access Token (required for Reels API)
    token = get_page_token(page_id, raw_token)

    print(f"[facebook] Layer 1: Initializing Reel upload (page_id={page_id})...")
    init_resp = requests.post(
        f"{GRAPH_API}/{page_id}/video_reels",
        params={"access_token": token},
        json={"upload_phase": "start"},
    )
    _raise_with_body(init_resp)
    video_id = init_resp.json()["video_id"]

    print(f"[facebook] Uploading video bytes (ID: {video_id})...")
    file_size = os.path.getsize(video_path)
    with open(video_path, "rb") as f:
        upload_resp = requests.post(
            f"{FB_UPLOAD_API}/{video_id}",  # rupload endpoint — required for Reels
            headers={
                "Authorization": f"OAuth {token}",
                "offset": "0",
                "file_size": str(file_size),
                "Content-Type": "video/mp4",
            },
            data=f,
            timeout=300,
        )
    _raise_with_body(upload_resp)

    print("[facebook] Publishing Reel...")
    publish_payload = {
        "upload_phase": "finish",
        "video_id": video_id,
        "title": "Quietlyy",
        "description": description,
        "video_state": "PUBLISHED",
    }
    ig_user_id = os.environ.get("INSTAGRAM_USER_ID")
    if ig_user_id:
        publish_payload["instagram_user_id"] = ig_user_id
        print("[facebook] Cross-posting to Instagram...")

    publish_resp = requests.post(
        f"{GRAPH_API}/{page_id}/video_reels",
        params={"access_token": token},
        json=publish_payload,
    )
    _raise_with_body(publish_resp)
    result = publish_resp.json()
    if ig_user_id:
        print(f"[facebook] Reel posted to Facebook + Instagram! ID: {result.get('id', video_id)}")
    else:
        print(f"[facebook] Reel posted to Facebook! ID: {result.get('id', video_id)}")
    return result


# ── Layer 2: Facebook Page Video (uses pages_manage_posts, no publish_video needed) ──
def post_as_video(video_path, description):
    page_id, raw_token = get_credentials()
    # Exchange System User token → Page Access Token
    token = get_page_token(page_id, raw_token)

    print(f"[facebook] Layer 2: Uploading as Page video (page_id={page_id})...")
    with open(video_path, "rb") as f:
        resp = requests.post(
            f"{GRAPH_API}/{page_id}/videos",
            params={"access_token": token},
            files={"source": ("quietlyy.mp4", f, "video/mp4")},
            data={"description": description, "title": "Quietlyy"},
            timeout=120,
        )
    _raise_with_body(resp)
    result = resp.json()
    print(f"[facebook] Video posted! ID: {result.get('id', 'unknown')}")
    return result


# ── Layer 3: Save for manual upload ──
def save_for_manual(video_path, description):
    output_dir = os.path.dirname(video_path)
    caption_path = os.path.join(output_dir, "manual_caption.txt")
    with open(caption_path, "w") as f:
        f.write(description)
    print(f"[facebook] Layer 3: Saved for manual upload")
    print(f"[facebook] Caption: {caption_path}")
    return {"status": "manual", "video": video_path, "caption": caption_path}


def post(video_path, topic, script_text, seo_metadata=None):
    """Main entry: post video with 3-layer fallback.
    seo_metadata: dict from generate_seo.generate_seo() — uses facebook.description if provided.
    """
    # Pre-flight: verify token and page before attempting upload
    try:
        verify_credentials()
    except Exception as e:
        print(f"[facebook] Pre-flight FAILED: {e}")
        print("[facebook] Skipping upload — credentials invalid.")
        return save_for_manual(video_path, build_description(topic, script_text))

    if seo_metadata and "facebook" in seo_metadata:
        description = seo_metadata["facebook"]["description"]
        print("[facebook] Using AI-optimised SEO description")
    else:
        description = build_description(topic, script_text)

    for layer_fn, name in [(post_as_reel, "Facebook Reel"), (post_as_video, "Facebook Video")]:
        try:
            return layer_fn(video_path, description)
        except Exception as e:
            print(f"[facebook] {name} failed: {e}")

    return save_for_manual(video_path, description)


if __name__ == "__main__":
    print("Facebook poster ready. Run via pipeline.py")
    print("Required env vars: FB_PAGE_ID, FB_PAGE_ACCESS_TOKEN")
