"""
Quietlyy -- Facebook/Instagram Poster
3-layer fallback: Facebook Reel -> Facebook Video -> manual save
SEO metadata and AI disclosure are generated by generate_seo.py.
"""

import os
import json
import requests

GRAPH_API = "https://graph.facebook.com/v22.0"
FB_UPLOAD_API = "https://rupload.facebook.com/video-upload/v22.0"


def get_credentials():
    page_id = os.environ.get("FB_PAGE_ID")
    token = os.environ.get("FB_PAGE_ACCESS_TOKEN")
    if not page_id or not token:
        raise ValueError("FB_PAGE_ID and FB_PAGE_ACCESS_TOKEN must be set")
    return page_id, token


def get_page_token(page_id, token):
    """Exchange any valid token for a Page Access Token (required for Reels API)."""
    resp = requests.get(
        f"{GRAPH_API}/{page_id}",
        params={"access_token": token, "fields": "access_token,name,id"},
        timeout=10,
    )
    if resp.status_code == 200:
        data = resp.json()
        page_token = data.get("access_token")
        if page_token and page_token != token:
            print(f"[facebook] Exchanged System User token for Page Access Token: '{data.get('name')}'")
            return page_token
    return token


def verify_credentials():
    """Pre-flight check: verify token works and page is accessible. Raises on failure."""
    page_id, token = get_credentials()
    print(f"[facebook] Pre-flight check (page_id={page_id})...")

    me_resp = requests.get(
        f"{GRAPH_API}/me",
        params={"access_token": token, "fields": "name,id"},
        timeout=10,
    )
    me = me_resp.json() if me_resp.content else {}
    if me_resp.status_code != 200 or "error" in me:
        err = me.get("error", {}) if isinstance(me, dict) else {}
        code = err.get("code", me_resp.status_code)
        msg = err.get("message", me_resp.text[:300])
        hint = " -- token expired, regenerate FB_PAGE_ACCESS_TOKEN in Meta Business Manager" if code == 190 else ""
        raise ValueError(f"Token invalid (code {code}): {msg}{hint}")
    print(f"[facebook] Token valid for: {me.get('name')} (id={me.get('id')})")

    page_resp = requests.get(
        f"{GRAPH_API}/{page_id}",
        params={"access_token": token, "fields": "name,id,fan_count"},
        timeout=10,
    )
    if page_resp.status_code != 200:
        raise ValueError(
            f"Page {page_id} not accessible -- {page_resp.status_code}: {page_resp.text[:300]}\n"
            f"HINT: FB_PAGE_ID should be the numeric Page ID from /me/accounts."
        )
    page = page_resp.json()
    print(f"[facebook] Page found: '{page.get('name')}' (id={page.get('id')}, followers={page.get('fan_count', 'unknown')})")


def build_description(topic, script_text):
    """Build a Whisprs-style viral caption — the script IS the hook, then hashtags."""
    lines = [line.strip() for line in script_text.split("\n") if line.strip()]
    caption = "\n".join(lines)

    # Emotional hashtag sets — rotate by topic hash so different videos get different tags
    _TAG_SETS = [
        "#emotional #feelings #deepthoughts #mentalhealth #selfcare #quotes #relateable #mindset",
        "#feelings #innerpeace #healing #emotionalhealth #lifequotes #mindfulness #selflove #quotes",
        "#unspoken #heartfelt #deepthoughts #emotions #healing #relateable #mentalhealthmatters #quotes",
        "#honesty #rawest #innermonologue #feelings #emotional #realquotes #selfawareness #mindset",
        "#healing #emotionalquotes #deepfeeling #vulnerability #feelings #mentalhealth #selflove #quotes",
    ]
    tag_idx = hash(topic) % len(_TAG_SETS)
    tags = _TAG_SETS[tag_idx]

    return (
        f"{caption}\n\n"
        f"— Quietlyy\n\n"
        f"#Quietlyy {tags}\n\n"
        f"AI assistance was used in the making of this video."
    )


def _raise_with_body(resp):
    try:
        resp.raise_for_status()
    except requests.HTTPError as e:
        raise requests.HTTPError(
            f"{e} | API response: {resp.text[:500]}", response=resp
        ) from e


def post_as_reel(video_path, description):
    page_id, raw_token = get_credentials()
    token = get_page_token(page_id, raw_token)

    print(f"[facebook] Layer 1: Initializing Reel upload (page_id={page_id})...")
    init_resp = requests.post(
        f"{GRAPH_API}/{page_id}/video_reels",
        params={"access_token": token},
        json={"upload_phase": "start"},
    )
    _raise_with_body(init_resp)
    video_id = init_resp.json()["video_id"]

    print(f"[facebook] Uploading video bytes (ID: {video_id})...")
    file_size = os.path.getsize(video_path)
    with open(video_path, "rb") as f:
        upload_resp = requests.post(
            f"{FB_UPLOAD_API}/{video_id}",
            headers={
                "Authorization": f"OAuth {token}",
                "offset": "0",
                "file_size": str(file_size),
                "Content-Type": "video/mp4",
            },
            data=f,
            timeout=300,
        )
    _raise_with_body(upload_resp)

    print("[facebook] Publishing Reel...")
    publish_resp = requests.post(
        f"{GRAPH_API}/{page_id}/video_reels",
        params={"access_token": token},
        json={
            "upload_phase": "finish",
            "video_id": video_id,
            "title": "Quietlyy",
            "description": description,
            "video_state": "PUBLISHED",
        },
    )
    _raise_with_body(publish_resp)
    result = publish_resp.json()
    print(f"[facebook] Reel posted! ID: {result.get('id', video_id)}")
    return result


def post_engagement_comment(post_id, comment_text):
    """Post the first comment AS THE PAGE on a published Reel/post.

    Engagement signal: pages that have the first comment as a question
    get 2-3x more reach (algorithm rewards comment threads). We can't
    PIN it via API (FB doesn't allow that), but being the first commenter
    is still strong.

    Returns True on success, False otherwise. Failure is non-fatal.
    """
    if not post_id or not comment_text:
        return False
    page_id, raw_token = get_credentials()
    token = get_page_token(page_id, raw_token)
    try:
        resp = requests.post(
            f"{GRAPH_API}/{post_id}/comments",
            params={"access_token": token},
            data={"message": comment_text},
            timeout=15,
        )
        if resp.status_code == 200:
            cid = resp.json().get("id", "?")
            print(f"[facebook] 💬 First comment posted (id={cid}): \"{comment_text[:60]}\"")
            return True
        print(f"[facebook] Comment failed: {resp.status_code} — {resp.text[:200]}")
    except Exception as e:
        print(f"[facebook] Comment error: {type(e).__name__}: {e}")
    return False


def post_as_video(video_path, description):
    page_id, raw_token = get_credentials()
    token = get_page_token(page_id, raw_token)

    print(f"[facebook] Layer 2: Uploading as Page video (page_id={page_id})...")
    with open(video_path, "rb") as f:
        resp = requests.post(
            f"{GRAPH_API}/{page_id}/videos",
            params={"access_token": token},
            files={"source": ("quietlyy.mp4", f, "video/mp4")},
            data={"description": description, "title": "Quietlyy"},
            timeout=120,
        )
    _raise_with_body(resp)
    result = resp.json()
    print(f"[facebook] Video posted! ID: {result.get('id', 'unknown')}")
    return result


def save_for_manual(video_path, description):
    output_dir = os.path.dirname(video_path)
    caption_path = os.path.join(output_dir, "manual_caption.txt")
    with open(caption_path, "w") as f:
        f.write(description)
    print(f"[facebook] Layer 3: Saved for manual upload")
    return {"status": "manual", "video": video_path, "caption": caption_path}


def post(video_path, topic, script_text, seo_metadata=None):
    """Main entry: post video with 3-layer fallback."""
    try:
        verify_credentials()
    except Exception as e:
        print(f"[facebook] Pre-flight FAILED: {e}")
        print("[facebook] Credentials invalid -- saving for manual upload. Check/regenerate FB_PAGE_ACCESS_TOKEN.")
        desc = build_description(topic, script_text)
        result = save_for_manual(video_path, desc)
        result["error"] = str(e)
        return result

    if seo_metadata and "facebook" in seo_metadata:
        description = seo_metadata["facebook"]["description"]
        print("[facebook] Using AI-optimised SEO description")
    else:
        description = build_description(topic, script_text)

    for layer_fn, name in [(post_as_reel, "Facebook Reel"), (post_as_video, "Facebook Video")]:
        try:
            return layer_fn(video_path, description)
        except Exception as e:
            print(f"[facebook] {name} failed: {e}")

    result = save_for_manual(video_path, description)
    result["error"] = "Both Reel and Video upload failed -- see log above"
    return result


if __name__ == "__main__":
    print("Facebook poster ready. Run via pipeline.py")
    print("Required env vars: FB_PAGE_ID, FB_PAGE_ACCESS_TOKEN")
